### PR TITLE
Code review

### PR DESCRIPTION
**Pull request by Jonast96**

### CODE REVIEW

**Comment by Fermain** [comment]
Critical Bug - Cannot log in with uppercase password. Please do not modify the user input for passwords, this must be exactly as the user entered it or they will not be able to log in. My test username has an uppercase password and I am therefore locked out of this account while using this app. Please resolve this before the review can continue.

**Comment by Jonast96** [comment]
> 

Should be working as intended now.

**Comment by Fermain** [comment]
JSDocs content needs some improvement. It isn't being used quite right. I've uploaded an example to the `teacher-review` branch where I will be making some other suggestions.

**Review by Fermain — CHANGES_REQUESTED** [review]
Hi, this is a good submission although the user experience can be improved. The required functionality is in place, and there is just some work to be done polishing off before delivery. Some of the JS Docs has been done perfectly but there are issues with other functions. Take a bit of time to go through my suggestions in the `teacher-review` branch and re-read the lesson content here.

Issues:
- Post thumbnails @Owner text should be replaced with author.name
- Issues with images. If no image is provided this can be removed from the request.
- Create post error handling, user is not alerted if this goes wrong
- Clicking on an author name should take you to their profile

**Pull request merged**
